import { Module } from '@nestjs/common';
import { CreateUserUsecase } from './usecases/create-user.usecase';
import { InfraModule } from 'src/infrastructure/infra.module';
import {
  GetAllAnimalSpecieUsecase,
  CreateAnimalSpecieUsecase,
  CreateAnimalBreedUsecase,
  GetAllAnimalBreedUsecase,
  GetAllClientUsecase,
  CreateClientUsecase,
  CreatePetUsecase,
  GetAllPetUsecase,
  GetAllAnimalSpecieByNameUsecase,
  SelectAnimalBreedUsecase,
  SelectAnimalSpecieUsecase,
  SelectClientUsecase,
  SelectPetUsecase,
  SelectUserUsecase,
  UpdateAnimalSpecieUsecase,
  UpdateAnimalBreedUsecase,
  UpdateUserUsecase,
  UpdatePetUsecase,
  UpdateClientUsecase,
  GetAnimalSpecieByIdUsecase,
} from './usecases';

@Module({
  imports: [InfraModule],
  providers: [
    SelectAnimalBreedUsecase,
    SelectAnimalSpecieUsecase,
    SelectPetUsecase,
    SelectClientUsecase,
    SelectUserUsecase,
    GetAllClientUsecase,
    GetAllAnimalSpecieUsecase,
    CreateAnimalSpecieUsecase,
    GetAllAnimalSpecieByNameUsecase,
    CreateUserUsecase,
    CreateAnimalBreedUsecase,
    GetAllAnimalBreedUsecase,
    CreateClientUsecase,
    CreatePetUsecase,
    GetAllPetUsecase,
    UpdateAnimalSpecieUsecase,
    UpdateAnimalBreedUsecase,
    UpdateUserUsecase,
    UpdatePetUsecase,
    UpdateClientUsecase,
    GetAnimalSpecieByIdUsecase,
  ],
  exports: [
    GetAllClientUsecase,
    SelectAnimalBreedUsecase,
    SelectAnimalSpecieUsecase,
    SelectPetUsecase,
    SelectUserUsecase,
    SelectClientUsecase,
    GetAllAnimalSpecieUsecase,
    CreateAnimalSpecieUsecase,
    GetAllAnimalSpecieByNameUsecase,
    CreateUserUsecase,
    CreateAnimalBreedUsecase,
    GetAllAnimalBreedUsecase,
    CreateClientUsecase,
    CreatePetUsecase,
    GetAllPetUsecase,
    UpdateAnimalSpecieUsecase,
    UpdateAnimalBreedUsecase,
    UpdateUserUsecase,
    UpdatePetUsecase,
    UpdateClientUsecase,
    GetAnimalSpecieByIdUsecase,
  ],
})
export class ApplicationModule {}
