import { Module } from '@nestjs/common';
import { InfraModule } from 'src/infrastructure/infra.module';
import {
  CreateAnimalBreedUsecase,
  CreateAnimalSpecieUsecase,
  CreateClientUsecase,
  CreatePetUsecase,
  CreateUserUsecase,
  GetAllAnimalBreedUsecase,
  GetAllAnimalSpecieByNameUsecase,
  GetAllAnimalSpecieUsecase,
  GetAllClientUsecase,
  GetAllPetUsecase,
  GetAnimalBreedByIdUsecase,
  GetAnimalSpecieByIdUsecase,
  GetClientByIdUsecase,
  GetPetByIdUsecase,
  SelectAnimalBreedUsecase,
  SelectAnimalSpecieUsecase,
  SelectClientUsecase,
  SelectPetUsecase,
  SelectUserUsecase,
  UpdateAnimalBreedUsecase,
  UpdateAnimalSpecieUsecase,
  UpdateClientUsecase,
  UpdatePetUsecase,
  UpdateUserUsecase,
} from './usecases';

@Module({
  imports: [InfraModule],
  providers: [
    SelectAnimalBreedUsecase,
    SelectAnimalSpecieUsecase,
    SelectPetUsecase,
    SelectClientUsecase,
    SelectUserUsecase,
    GetAllClientUsecase,
    GetAllAnimalSpecieUsecase,
    CreateAnimalSpecieUsecase,
    GetAllAnimalSpecieByNameUsecase,
    CreateUserUsecase,
    CreateAnimalBreedUsecase,
    GetAllAnimalBreedUsecase,
    CreateClientUsecase,
    CreatePetUsecase,
    GetAllPetUsecase,
    UpdateAnimalSpecieUsecase,
    UpdateAnimalBreedUsecase,
    UpdateUserUsecase,
    UpdatePetUsecase,
    UpdateClientUsecase,
    GetAnimalSpecieByIdUsecase,
    GetAnimalBreedByIdUsecase,
    GetPetByIdUsecase,
    GetClientByIdUsecase
  ],
  exports: [
    GetAllClientUsecase,
    SelectAnimalBreedUsecase,
    SelectAnimalSpecieUsecase,
    SelectPetUsecase,
    SelectUserUsecase,
    SelectClientUsecase,
    GetAllAnimalSpecieUsecase,
    CreateAnimalSpecieUsecase,
    GetAllAnimalSpecieByNameUsecase,
    CreateUserUsecase,
    CreateAnimalBreedUsecase,
    GetAllAnimalBreedUsecase,
    CreateClientUsecase,
    CreatePetUsecase,
    GetAllPetUsecase,
    UpdateAnimalSpecieUsecase,
    UpdateAnimalBreedUsecase,
    UpdateUserUsecase,
    UpdatePetUsecase,
    UpdateClientUsecase,
    GetAnimalSpecieByIdUsecase,
    GetAnimalBreedByIdUsecase,
    GetPetByIdUsecase,
    GetClientByIdUsecase
  ],
})
export class ApplicationModule {}
